name: Daily Checkin
on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  my_job:
    name: Checkin
    runs-on: ubuntu-latest
    env:
      BOTID: ${{ secrets.BOTID }}
      CHATID: ${{ secrets.CHATID }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWD: ${{ secrets.PASSWD }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        pip install asyncio playwright requests
        python -m playwright install firefox
        python report.py "$BOTID" "$CHATID" "$USERNAME" "$PASSWD"
